service: odyssey-backend

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-2
  memorySize: 128
  timeout: 30

# you can add packaging information here
# package:
#  include:
#    - node_modules
#  exclude:
#    - package.json
#  artifact: my-service-code.zip

functions:
  userExists:
    handler: dist/handler.user_exists
    events:
      - http:
          path: user-exists
          method: get
          cors: true
  newUser:
    handler: dist/handler.new_user
    events:
      - http:
          path: new-user
          method: post
          cors: true
  refresh:
    handler: dist/handler.refresh
    events:
      - http:
          path: refresh
          method: post
          cors: true
  randBills:
    handler: dist/handler.rand_bills
    events:
      - http:
          path: rand-bills
          method: get
          cors: true
  likedBills:
    handler: dist/handler.liked_bills
    events:
      - http:
          path: liked-bills
          method: post
          cors: true
  search:
    handler: dist/handler.search
    events:
      - http:
          path: search
          method: post
          cors: true
  like:
    handler: dist/handler.like
    events:
      - http:
          path: like
          method: post
          cors: true
  vote:
    handler: dist/handler.vote
    events:
      - http:
          path: vote
          method: post
          cors: true
  addComment:
    handler: dist/handler.add_comment
    events:
      - http:
          path: add-comment
          method: post
          cors: true
  getBillData:
    handler: dist/handler.get_bill_data
    events:
      - http:
          path: get-bill-data
          method: post
          cors: true
  likeComment:
    handler: dist/handler.like_comment
    events:
      - http:
          path: like-comment
          method: post
          cors: true
  uploadPFP:
    handler: dist/handler.upload_pfp
    events:
      - http:
          path: upload-pfp
          method: post
          cors: true
  deleteComment:
    handler: dist/handler.delete_comment
    events:
      - http:
          path: delete-comment
          method: post
          cors: true
  updateProfile:
    handler: dist/handler.update_profile
    events:
      - http:
          path: update-profile
          method: post
          cors: true
  deleteUser:
    handler: dist/handler.delete_user
    events:
      - http:
          path: delete-user
          method: post
          cors: true
  emailRep:
    handler: dist/handler.email_rep
    events:
      - http:
          path: email-rep
          method: post
          cors: true

plugins:
  - serverless-offline
#   you can add any of the following events
#   events:
#     - http:
#         path: users/create
#         method: get
#     - s3: ${bucket}
#     - schedule: rate(10 minutes)
#     - sns: greeter-topic

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
