service: odyssey

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-2
  memorySize: 128
  timeout: 30

# you can add packaging information here
# package:
#  include:
#    - node_modules
#  exclude:
#    - package.json
#  artifact: my-service-code.zip

functions:
  getReps:
    handler: dist/handler.get_reps
    events:
      - http:
          path: get-reps
          method: get
          cors: true
#   you can add any of the following events
#   events:
#     - http:
#         path: users/create
#         method: get
#     - s3: ${bucket}
#     - schedule: rate(10 minutes)
#     - sns: greeter-topic

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
